version: "3.9"
services:
  db:
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 300M
    container_name: db-certamen2
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: certamen2_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-certamen2
  web:
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 300M
    container_name: certamen2-web
    depends_on:
      - db
    ports:
      - "8083:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-certamen2
networks:
  net-certamen2:
    
